# Generated by Django 4.2.3 on 2023-08-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank='', max_length=100, null='')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank='', max_length=100, null='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank='', max_length=100, null='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank='', max_length=100, null='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('publication_Date', models.DateTimeField()),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('content', models.TextField(max_length=300)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article_service.category')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article_service.continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article_service.country')),
                ('tag', models.ManyToManyField(to='Article_service.tag')),
            ],
        ),
    ]
