# Generated by Django 4.2.3 on 2023-08-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='Reporter',
        ),
    ]
